export const data = [
    {
        "site": "Site 1",
        "Plot 1": 0,
        "Plot 2": 0,
        "Plot 3": 0,
        "Plot 4": 0,
        "Plot 5": 0,
        "Plot 6": 0,
    },
    {
        "site": "Road 1",
        "Plot 1": 100,
        "Plot 2": 100,
        "Plot 3": 100,
        "Plot 4": 100,
        "Plot 5": 100,
        "Plot 6": 100,
    },
    {
        "site": "Site 2",
        "Plot 1": 0,
        "Plot 2": 0,
        "Plot 3": 0,
        "Plot 4": 0,
        "Plot 5": 0,
        "Plot 6": 0,
    },
    {
        "site": "Site 3",
        "Plot 1": 0,
        "Plot 2": 0,
        "Plot 3": 0,
        "Plot 4": 0,
        "Plot 5": 0,
        "Plot 6": 0,
    },
    {
        "site": "Road 2",
        "Plot 1": 100,
        "Plot 2": 100,
        "Plot 3": 100,
        "Plot 4": 100,
        "Plot 5": 100,
        "Plot 6": 100,
    },
    {
        "site": "Site 4",
        "Plot 1": 0,
        "Plot 2": 0,
        "Plot 3": 0,
        "Plot 4": 0,
        "Plot 5": 0,
        "Plot 6": 0,
    },
    {
        "site": "Site 5",
        "Plot 1": 0,
        "Plot 2": 0,
        "Plot 3": 0,
        "Plot 4": 0,
        "Plot 5": 0,
        "Plot 6": 0,
    },
    {
        "site": "Road 3",
        "Plot 1": 100,
        "Plot 2": 100,
        "Plot 3": 100,
        "Plot 4": 100,
        "Plot 5": 100,
        "Plot 6": 100,
    },
    {
        "site": "Site 6",
        "Plot 1": 0,
        "Plot 2": 0,
        "Plot 3": 0,
        "Plot 4": 0,
        "Plot 5": 0,
        "Plot 6": 0,
    },
    {
        "site": "Site 7",
        "Plot 1": 0,
        "Plot 2": 0,
        "Plot 3": 0,
        "Plot 4": 0,
        "Plot 5": 0,
        "Plot 6": 0,
    },
    {
        "site": "Road 4",
        "Plot 1": 100,
        "Plot 2": 100,
        "Plot 3": 100,
        "Plot 4": 100,
        "Plot 5": 100,
        "Plot 6": 100,
    },
    {
        "site": "site 8",
        "Plot 1": 0,
        "Plot 2": 0,
        "Plot 3": 0,
        "Plot 4": 0,
        "Plot 5": 0,
        "Plot 6": 0,
    }
]